export const allData = [
  // {
  //   id: "0009",
  //   header: "deneme deneme",
  //   info: "Tailored to its users and their activities, allows invest each euro in what you really need, the most economical way of making architecture.lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam lorem",
  //   description:
  //     "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam lorem lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremvlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam lorem lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam lorem lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremvlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam lorem  ",
  //   type: "evler",
  //   mainImage: "/1.jpg",
  //   images: ["/1.jpg", "/2.jpg", "/3.jpg"],
  // },
  // {
  //   id: "0008",
  //   header: "gethr5465",
  //   info: "Tailored to its users and their activities, allows invest each euro in what you really need, the most economical way of making architecture.",
  //   description: "",
  //   type: "reformlar",
  //   mainImage: "/1.jpg",
  //   images: ["/1.jpg", "/2.jpg", "/3.jpg"],
  // },
  // {
  //   id: "0007",
  //   header: "allows inveseherht45h4t",
  //   info: "Tailored to its users and their activities, allows invest each euro in what you really need, the most economical way of making architecture.",
  //   description: "",
  //   type: "evler",
  //   mainImage: "/1.jpg",
  //   images: ["/1.jpg", "/2.jpg", "/3.jpg"],
  // },
  {
    id: "0006",
    header: "27728 ADA 7 PARSEL",
    info: "9 Daire",
    description: "",
    type: "konut",
    mainImage: "/Keklik_pinari_04.webp",
    images: [
      "/Keklik_pinari_01.webp",
      "/Keklik_pinari_02.webp",
      "/Keklik_pinari_03.webp",
      "/Keklik_pinari_04.webp",
      "/Keklik_pinari_05.webp",
    ],
  },
  {
    id: "0005",
    header: "TOBB Kolej İnşaatı",
    info: "İşveren: TOBEV",
    description: "Sözleşme Yılı : 2024",
    type: "taahhut",
    mainImage: "/TOBB_kolej_insaati_02.webp",
    images: [
      "/TOBB_kolej_insaati_01.webp",
      "/TOBB_kolej_insaati_02.webp",
      "/TOBB_kolej_insaati_03.webp",
    ],
  },
  {
    id: "0004",
    header: "TOBB ETÜ Kampüsü Çevre Düzenlemesi ve Otopark İnşaatı Yapımı İşi",
    info: "İşveren: TOBB Ekonomi Ve Teknoloji Üniversitesi",
    description: "Sözleşme Yılı : 2019",
    type: "taahhut",
    mainImage: "/TobbEtu_kampusu_cevre_duzenlemesi_01.webp",
    images: [
      "/TobbEtu_kampusu_cevre_duzenlemesi_01.webp",
      "TobbEtu_kampusu_cevre_duzenlemesi_02.webp",
    ],
  },
  {
    id: "0003",
    header: "AB Kampüs Mutfak",
    info: "",
    description: "",
    type: "taahhut",
    mainImage: "/AB_kampus_mutfak_01.webp",
    images: [
      "/AB_kampus_mutfak_01.webp",
      "/AB_kampus_mutfak_02.webp",
      "/AB_kampus_mutfak_03.webp",
      "/AB_kampus_mutfak_04.webp",
      "/AB_kampus_mutfak_05.webp",
      "/AB_kampus_mutfak_06.webp",
      "/AB_kampus_mutfak_07.webp",
    ],
  },
  {
    id: "0002",
    header:
      "Ahiboz Hububat Alım Tesisleri Çelik Silolara Ait Alt Yapı Ve Drenaj İşleri Gimat Et Teşhir Salonu Tadilat Onarım İşleri",
    info: "İşveren: Türkiye Odalar ve Borsalar Birliği ",
    description: "Sözleşme Yılı : 2020",
    type: "taahhut",
    mainImage: "/Ahiboz_Hububat_Alım_Tesisleri_01.webp",
    images: [
      "/Ahiboz_Hububat_Alım_Tesisleri_01.webp",
      "/Ahiboz_Hububat_Alım_Tesisleri_02.webp",
    ],
  },
  {
    id: "0001",
    header: "TOBB Karaman Fen Lisesi Çevre Düzenlemesi İnşaatı ",
    info: "İşveren: Türkiye Odalar ve Borsalar Birliği",
    description: "",
    type: "taahhut",
    mainImage: "/tobb_karaman_fen_03.webp",
    images: [
      "/tobb_karaman_fen_03.webp",
      "/tobb_karaman_fen_02.webp",
      "/tobb_karaman_fen_01.webp",
    ],
  },
];
