export const allData = [
  {
    id: "0009",
    header: "deneme deneme",
    info: "Tailored to its users and their activities, allows invest each euro in what you really need, the most economical way of making architecture.lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam lorem",
    description:
      "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam lorem lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremvlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam lorem lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam lorem lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam loremvlorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Nullam lorem  ",
    type: "evler",
    mainImage: "/1.jpg",
    images: ["/1.jpg", "/2.jpg", "/3.jpg"],
  },
  {
    id: "0008",
    header: "gethr5465",
    info: "Tailored to its users and their activities, allows invest each euro in what you really need, the most economical way of making architecture.",
    description: "",
    type: "reformlar",
    mainImage: "/1.jpg",
    images: ["/1.jpg", "/2.jpg", "/3.jpg"],
  },
  {
    id: "0007",
    header: "allows inveseherht45h4t",
    info: "Tailored to its users and their activities, allows invest each euro in what you really need, the most economical way of making architecture.",
    description: "",
    type: "evler",
    mainImage: "/1.jpg",
    images: ["/1.jpg", "/2.jpg", "/3.jpg"],
  },
  {
    id: "0006",
    header: "08wefwewdfbdgne4g",
    info: "Tailored to its users and their activities, allows invest each euro in what you really need, the most economical way of making architecture.",
    description: "",
    type: "evler",
    mainImage: "/1.jpg",
    images: ["/1.jpg", "/2.jpg", "/3.jpg"],
  },
  {
    id: "0005",
    header: "gethr54erger65",
    info: "Tailored to its users and their activities, allows invest each euro in what you really need, the most economical way of making architecture.",
    description: "",
    type: "reformlar",
    mainImage: "/1.jpg",
    images: ["/1.jpg", "/2.jpg", "/3.jpg"],
  },
  {
    id: "0004",
    header: "allows invest  wfgergergwg3gre",
    info: "Tailored to its users and their activities, allows invest each euro in what you really need, the most economical way of making architecture.",
    description: "",
    type: "evler",
    mainImage: "/1.jpg",
    images: ["/1.jpg", "/2.jpg", "/3.jpg"],
  },
  {
    id: "0003",
    header: "08023 Architeergergctsg4hrthftnhrtnr",
    info: "Tailored to its users and their activities, allows invest each euro in what you really need,st each euro in what you really the most economical way of making architecture.",
    description: "",
    type: "evler",
    mainImage: "/1.jpg",
    images: ["/1.jpg", "/2.jpg", "/3.jpg"],
  },
  {
    id: "0002",
    header:
      "Ahiboz Hububat Alım Tesisleri Çelik Silolara Ait Alt Yapı Ve Drenaj İşleri Gimat Et Teşhir Salonu Tadilat Onarım İşleri",
    info: "İşveren: Türkiye Odalar ve Borsalar Birliği ",
    description: "Sözleşme Yılı : 2020",
    type: "reformlar",
    mainImage: "/Ahiboz_Hububat_Alım_Tesisleri_01.webp",
    images: [
      "/Ahiboz_Hububat_Alım_Tesisleri_01.webp",
      "/Ahiboz_Hububat_Alım_Tesisleri_02.webp",
    ],
  },
  {
    id: "0001",
    header: "TOBB Karaman Fen Lisesi Çevre Düzenlemesi İnşaatı ",
    info: "İşveren: Türkiye Odalar ve Borsalar Birliği",
    description: "",
    type: "evler",
    mainImage: "/tobb_karaman_fen_03.webp",
    images: [
      "/tobb_karaman_fen_03.webp",
      "/tobb_karaman_fen_02.webp",
      "/tobb_karaman_fen_01.webp",
    ],
  },
];
