import { Abel, Raleway } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import Header from "./components/Header";
import Slider from "./components/MainSlider";
import Projects from "./components/Projects";
import Footer from "./components/Footer";

const abel = Abel({
  weight: "400",
});

const raleway = Raleway({
  weight: "400",
});

export const metadata = {
  title: "DMG",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Header />

        {children}
        <Footer />
        <ToastContainer />
      </body>
    </html>
  );
}
